# **LangChain으로 데이터 전처리하기**

이 실습은 서울시 아파트 거래 데이터를 기반으로, LangChain과 OpenAI LLM을 활용해 자연어를 통한 데이터 전처리를 자동화합니다.

실무에서 데이터 분석의 대부분을 차지하는 전처리 과정은 반복적이고 복잡한 작업이 많습니다. 이 실습에서는 사용자가 자연어로 전처리 목적을 입력하면, 모델이 현재 데이터프레임의 구조를 자동으로 분석하고, 그에 맞는 정확한 pandas 전처리 코드를 자동 생성해주는 흐름을 구성합니다.

전통적인 코딩 중심의 전처리 방식에서 벗어나, LLM과 LangChain의 기능을 결합하여 전처리 효율을 극대화합니다.

## 학습 목표
- 서울시 아파트 거래 데이터를 분석 대상 데이터셋으로 이해하고, 전처리 작업의 필요성을 파악할 수 있다.
- LangChain과 LLM을 연계하여 자연어 전처리 지시를 통해 pandas 코드 자동 생성을 구현할 수 있다.
- 데이터 전처리를 자동화하는 체인을 구성하여, 반복적인 작업을 효율화하는 방법을 학습할 수 있다.
- LLM이 생성한 전처리 코드를 마크다운 형식으로 출력하고, 직접 실행하여 데이터프레임을 정제할 수 있다.

이번 실습에서는 OpenAI의 `gpt-4o-mini` 모델을 사용하기 때문에 본격적인 실습에 앞서 OpenAI API 키를 설정합니다.

In [1]:
import os

os.environ["OPENAI_API_KEY"] = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3ODExODE2MzIsIm5iZiI6MTc4MTE4MTYzMiwiZXhwIjoxNzgxNzA4Mzk5LCJrZXlfaWQiOiIyNDExZDMyMy04NjkzLTQ5NzktOThlMS00MjE2ZWY5YmQ5NjQifQ.t7kVir7TZl4SpgM32IRvktL-rfIndh1UVJb8FeGdmLM"

## 데이터 로드

[2022년 서울 아파트 거래 데이터](http://rtdown.molit.go.kr/)를 분석해보겠습니다.

In [3]:
import pandas as pd

path = "./seoul_apart_2022.csv"
df = pd.read_csv(path)
df

,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도,도로명,해제사유발생일,거래유형,중개사소재지
0,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성아파트1동~8동,79.97,202204,12,220000.0,4,1987.0,언주로 3,NaN,중개거래,서울 강남구
1,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성아파트1동~8동,79.97,202204,21,220000.0,2,1987.0,언주로 3,NaN,중개거래,서울 강남구
2,서울특별시 강남구 개포동,658-1,658.0,1.0,개포6차우성아파트1동~8동,79.97,202205,27,216000.0,2,1987.0,언주로 3,NaN,중개거래,서울 강남구
3,서울특별시 강남구 개포동,1282,1282.0,0.0,개포래미안포레스트,102.32,202204,1,369000.0,13,2020.0,개포로 264,NaN,중개거래,"서울 강남구, 서울 양천구"
4,서울특별시 강남구 개포동,1282,1282.0,0.0,개포래미안포레스트,136.06,202205,2,420000.0,17,2020.0,개포로 264,NaN,중개거래,서울 강남구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12679,서울특별시 중랑구 중화동,450,450.0,0.0,한신아파트(103~109),59.76,202203,27,73000.0,20,1997.0,동일로 752,NaN,중개거래,서울 중랑구
12680,서울특별시 중랑구 중화동,450,450.0,0.0,한신아파트(103~109),59.76,202207,20,74000.0,3,1997.0,동일로 752,NaN,중개거래,서울 중랑구
12681,서울특별시 중랑구 중화동,450,450.0,0.0,한신아파트(103~109),84.03,202207,27,91500.0,12,1997.0,동일로 752,NaN,중개거래,서울 중랑구
12682,서울특별시 중랑구 중화동,274-51,274.0,51.0,한영(101),84.69,202204,9,49900.0,7,2003.0,동일로144길 74,NaN,중개거래,서울 중랑구
12683,서울특별시 중랑구 중화동,11월 07일,11.0,7.0,현대휴앤미(102동),76.43,202204,23,53000.0,6,2007.0,봉화산로27가길 19,NaN,중개거래,서울 중랑구

In [4]:
type(df)

pandas.DataFrame

## 모델 및 체인 설정

OpenAI의 GPT 모델을 LangChain에서 사용할 수 있도록 도와주는 `ChatOpenAI` 클래스를 불러옵니다. 여기서는 `gpt-4o-mini` 모델을 사용하고 `temperature`는 0으로 설정하여 일관된 답변을 얻을 수 있도록 하였습니다.

#### Temperature란?
- 다양성 정도를 나타내며 높을수록 창의적인 결과물을 만들어줍니다.
- Temperature 값이 높을수록 모델이 생성하는 문장이 더 다양해지고, 값이 낮을수록 더 일관성 있는 문장이 생성 됩니다.

In [6]:
from langchain_openai import ChatOpenAI

llm = ChatOpenAI(model="openai/gpt-5.4", temperature=0, base_url="https://mlapi.run/8ebfcef5-8d34-4355-a8d9-89f9253acd2b/v1")

사용자의 요청을 구조적으로 템플릿화해서 사용할 수 있게 해주는 `PromptTemplate`을 불러옵니다. 그리고 사용자의 요청에 따라 코드를 생성해줄 프롬프트를 정의합니다.

이 프롬프트는 LangChain의 LLM에게 pandas 기반 전처리 코드를 자동 생성하라고 요청합니다.

프롬프트의 핵심 설정은 다음과 같습니다.
- 데이터분석가 역할 부여
- 사용하는 데이터 프레임(`df`)의 구조(컬럼명, 타입 등)를 `{structure}`로 전달하여 LLM이 상황을 이해할 수 있도록 함
- 전처리 목적을 충실히 수행
- LLM이 설명이나 불필요한 서술 없이 주석 포함된 pandas 코드만 출력하게 유도

이렇게 강하게 제약을 주어야 GPT가 실행 가능한 코드만 반환하도록 유도할 수 있습니다.

In [7]:
from langchain_core.prompts import PromptTemplate

prompt = PromptTemplate(
    input_variables=["structure", "query"],
    template="""
            당신은 숙련된 데이터 분석가입니다.
            아래는 사용자의 데이터프레임 구조입니다:

            {structure}

            이 구조를 바탕으로 다음 요청에 해당하는 pandas 전처리 코드를 작성하세요:
            "{query}"

            코드만 출력하고, 실행하지 마세요. 반드시 주석 포함해서 작성하세요.
            """,
)

#### `summarize_df_structure` 함수

LLM과 프롬프트는 모두 설정했습니다.

이후 우리는 LLM이 프롬프트에 따라 생성한 코드를 직접 실행하며 데이터를 전처리할 것입니다. 하지만 현재의 LLM 구조는 전처리된 데이터를 직접 분석할 수 없습니다. LLM이 정확한 전처리 코드를 생성하려면 앞서 불러온 **2022년 서울 아파트 거래 데이터**를 반영해야 합니다.

따라서 이 `summarize_df_structure` 함수는 현재 상태의 DataFrame을 요약하여 LLM에 전달할 수 있도록 문자열로 정리해 줍니다.

In [8]:
def summarize_df_structure(df: pd.DataFrame) -> str:
    structure = f"컬럼 목록: {list(df.columns)}\n"
    structure += "데이터 타입:\n" + df.dtypes.to_string() + "\n"
    structure += "결측치 개수:\n" + df.isnull().sum().to_string() + "\n"
    return structure

#### `StrOutputParser` 생성

그리고 LLM이 생성한 메시지 중 코드만 출력할 수 있도록 `StrOutputParser`를 생성하겠습니다. 이때 `RunnableLambda` 클래스로 파이썬의 lambda 함수나 일반 함수를 LangChain의 체인 요소로 바꿔줍니다.

- 역할 : 내부적으로 `df`의 구조를 요약
- 입력 : `query`(사용자의 자연어 요청)
- 출력 : LLM에 전달할 `dict` 형태로 `{structure, query}` 구성

In [10]:
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnableLambda

result_parser = StrOutputParser()

structure_generator = RunnableLambda(
    lambda query: {"structure": summarize_df_structure(df), "query": query}
)

#### LLM의 응답에서 코드 블록만 출력

LLM이 생성한 응답에서 코드만 깔끔하게 추출하고, 이를 보기 좋게 출력하는 데 사용하기 위해 `extract_code_block` 함수와 `show_code_as_markdown` 함수를 작성합니다.

LangChain을 통해 생성된 응답은 종종 마크다운 형식으로 감싸진 상태로 제공되므로, 이를 후처리해야 실제로 보기 쉬운 코드로 만들 수 있습니다.

In [11]:
from IPython.display import Markdown, display
import re


def extract_code_block(response: str) -> str:
    match = re.search(r"```(?:python)?(.*?)```", response, re.DOTALL)
    return match.group(1).strip() if match else response.strip()


def show_code_as_markdown(code: str):
    display(Markdown(f"```python\n{code}\n```"))

이제 모든 구성 요소들을 체인으로 연결하겠습니다.

In [12]:
code_extractor = RunnableLambda(extract_code_block)
markdown_renderer = RunnableLambda(show_code_as_markdown)

code_chain = (
    structure_generator
    | prompt
    | llm
    | result_parser
    | StrOutputParser()
    | code_extractor
    | markdown_renderer
)

## EDA 수행

EDA는 **Exploratory Data Analysis**의 약어로 데이터 분석 과정에서 데이터를 탐색하고 이해하는 과정을 말합니다.

### 데이터 살펴보기

In [15]:
response = code_chain.invoke("전체 데이터의 갯수와 자료형 등을 확인해줄래?")

response

```python
# 데이터프레임 전체 행/열 개수 확인
print("데이터 크기(shape):", df.shape)

# 각 컬럼의 데이터 타입 확인
print("\n컬럼별 데이터 타입:")
print(df.dtypes)

# 데이터프레임 기본 정보 확인
print("\n데이터프레임 기본 정보:")
df.info()

# 기술통계 요약 확인
print("\n수치형 컬럼 기술통계:")
print(df.describe())

# 범주형(문자형) 컬럼 포함 전체 기술통계 확인
print("\n전체 컬럼 기술통계:")
print(df.describe(include='all'))
```

In [16]:
# 이 곳에 LLM이 알려준 최종 코드 결과를 붙여넣습니다.
# 데이터프레임 전체 행/열 개수 확인
print("데이터 크기(shape):", df.shape)

# 각 컬럼의 데이터 타입 확인
print("\n컬럼별 데이터 타입:")
print(df.dtypes)

# 데이터프레임 기본 정보 확인
print("\n데이터프레임 기본 정보:")
df.info()

# 기술통계 요약 확인
print("\n수치형 컬럼 기술통계:")
print(df.describe())

# 범주형(문자형) 컬럼 포함 전체 기술통계 확인
print("\n전체 컬럼 기술통계:")
print(df.describe(include='all'))

데이터 크기(shape): (12684, 15)

컬럼별 데이터 타입:
시군구             str
번지              str
본번          float64
부번          float64
단지명             str
전용면적(㎡)     float64
계약년월          int64
계약일           int64
거래금액(만원)    float64
층             int64
건축년도        float64
도로명             str
해제사유발생일     float64
거래유형            str
중개사소재지          str
dtype: object

데이터프레임 기본 정보:
<class 'pandas.DataFrame'>
RangeIndex: 12684 entries, 0 to 12683
Data columns (total 15 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   시군구       12684 non-null  str
 1   번지        12681 non-null  str
 2   본번        12682 non-null  float64
 3   부번        12682 non-null  float64
 4   단지명       12684 non-null  str
 5   전용면적(㎡)   12684 non-null  float64
 6   계약년월      12684 non-null  int64
 7   계약일       12684 non-null  int64
 8   거래금액(만원)  12651 non-null  float64
 9   층         12684 non-null  int64
 10  건축년도      12682 non-null  float64
 11  도로명       12684 non-null  str
 12  해제사유발생일   715 non-null    float64
 13  거래유형      12684 non-null  str
 14  중개사소재지    12684 non-null  str
dtypes: float64(6), int64(3), str(6)
memory usage: 2.7 MB

수치형 컬럼 기술통계:
                 본번            부번       전용면적(㎡)           계약년월           계약일  \
count  12682.000000  12682.000000  12684.000000   12684.000000  12684.000000
mean     561.214083     10.926116     66.652648  202205.730211     16.104068
std      546.871123     73.221227     38.611786       3.259286      8.579843
min        0.000000      0.000000     11.330000  202201.000000      1.000000
25%      150.000000      0.000000     39.510000  202203.000000      9.000000
50%      466.000000      0.000000     59.970000  202205.000000     16.000000
75%      777.000000      3.000000     84.920000  202208.000000     23.000000
max     4974.000000   2066.000000    301.470000  202212.000000     31.000000

           거래금액(만원)             층          건축년도       해제사유발생일
count  1.265100e+04  12684.000000  12682.000000  7.150000e+02
mean   9.756214e+04      9.286266   2004.780792  2.022258e+07
std    9.474038e+04      6.302898     11.670889  3.720448e+03
min    6.700000e+03     -1.000000   1961.000000  2.022011e+07
25%    3.900000e+04      5.000000   1997.000000  2.022053e+07
50%    7.500000e+04      8.000000   2004.000000  2.022092e+07
75%    1.200000e+05     13.000000   2014.000000  2.022122e+07
max    1.450000e+06     64.000000   2022.000000  2.023052e+07

전체 컬럼 기술통계:
                  시군구     번지            본번            부번    단지명       전용면적(㎡)  \
count           12684  12681  12682.000000  12682.000000  12684  12684.000000
unique            299   2723           NaN           NaN   3253           NaN
top     서울특별시 노원구 상계동    522           NaN           NaN  아이유하임           NaN
freq              370    138           NaN           NaN    135           NaN
mean              NaN    NaN    561.214083     10.926116    NaN     66.652648
std               NaN    NaN    546.871123     73.221227    NaN     38.611786
min               NaN    NaN      0.000000      0.000000    NaN     11.330000
25%               NaN    NaN    150.000000      0.000000    NaN     39.510000
50%               NaN    NaN    466.000000      0.000000    NaN     59.970000
75%               NaN    NaN    777.000000      3.000000    NaN     84.920000
max               NaN    NaN   4974.000000   2066.000000    NaN    301.470000

                 계약년월           계약일      거래금액(만원)             층          건축년도  \
count    12684.000000  12684.000000  1.265100e+04  12684.000000  12682.000000
unique            NaN           NaN           NaN           NaN           NaN
top               NaN           NaN           NaN           NaN           NaN
freq              NaN           NaN           NaN           NaN           NaN
mean    202205.730211     16.104068  9.756214e+04      9.286266   2004.780792
std          3.259286      8.579843  9.474038e+04      6.302898     11.670889
min     202201.000000      1.000000  6.700000e+03     -1.000000   1961.000000
25%     202203.000000      9.000000  3.900000e+04      5.000000   1997.000000
50%     202205.000000     16.000000  7.500000e+04      8.000000   2004.000000
75%     202208.000000     23.000000  1.200000e+05     13.000000   2014.000000
max     202212.000000     31.000000  1.450000e+06     64.000000   2022.000000

            도로명       해제사유발생일   거래유형 중개사소재지
count     12684  7.150000e+02  12684  12684
unique     3710           NaN      2    363
top     독산로 293           NaN   중개거래      -
freq        135           NaN  10732   1966
mean        NaN  2.022258e+07    NaN    NaN
std         NaN  3.720448e+03    NaN    NaN
min         NaN  2.022011e+07    NaN    NaN
25%         NaN  2.022053e+07    NaN    NaN
50%         NaN  2.022092e+07    NaN    NaN
75%         NaN  2.022122e+07    NaN    NaN
max         NaN  2.023052e+07    NaN    NaN

### 데이터 전처리

#### 컬럼 데이터 제거

분석에 크게 의미가 없다고 판단되는 잉여 컬럼을 제거합니다.

`"삭제해줄래?"`라고 하면 LLM 내에서 삭제된 데이터프레임을 보여주기만 할 뿐, notebook 환경에서는 반영되지 않습니다.

`"코드를 짜줄래?"`와 같은 형식으로 LLM으로부터 코드를 얻어내고, 해당 코드를 복사+붙여넣기 하여 notebook에서 실행시키는 방식으로 진행합니다.

In [17]:
response = code_chain.invoke(
    "데이터 분석 과정에서 활용하기 어려운 컬럼들인 해제사유발생일, 중개사소재지, 번지, 본번, 부번, 도로명, 거래유형 컬럼들을 삭제해주는 코드를 짜줄래?"
)

response

```python
# 분석 활용도가 낮은 컬럼 삭제
cols_to_drop = ['해제사유발생일', '중개사소재지', '번지', '본번', '부번', '도로명', '거래유형']

# 원본 데이터프레임(df)에서 해당 컬럼들 제거
df = df.drop(columns=cols_to_drop)

# 삭제 결과 확인용
df.head()
```

In [18]:
# 이 곳에 LLM이 알려준 최종 코드 결과를 붙여넣습니다.

# 분석 활용도가 낮은 컬럼 삭제
cols_to_drop = ['해제사유발생일', '중개사소재지', '번지', '본번', '부번', '도로명', '거래유형']

# 원본 데이터프레임(df)에서 해당 컬럼들 제거
df = df.drop(columns=cols_to_drop)

# 삭제 결과 확인용
df.head()

             시군구             단지명  전용면적(㎡)    계약년월  계약일  거래금액(만원)   층    건축년도
0  서울특별시 강남구 개포동  개포6차우성아파트1동~8동    79.97  202204   12  220000.0   4  1987.0
1  서울특별시 강남구 개포동  개포6차우성아파트1동~8동    79.97  202204   21  220000.0   2  1987.0
2  서울특별시 강남구 개포동  개포6차우성아파트1동~8동    79.97  202205   27  216000.0   2  1987.0
3  서울특별시 강남구 개포동       개포래미안포레스트   102.32  202204    1  369000.0  13  2020.0
4  서울특별시 강남구 개포동       개포래미안포레스트   136.06  202205    2  420000.0  17  2020.0

notebook 환경에서 데이터프레임은 아직 변경되지 않은 것을 확인해볼 수 있습니다.

In [19]:
df

,시군구,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도
0,서울특별시 강남구 개포동,개포6차우성아파트1동~8동,79.97,202204,12,220000.0,4,1987.0
1,서울특별시 강남구 개포동,개포6차우성아파트1동~8동,79.97,202204,21,220000.0,2,1987.0
2,서울특별시 강남구 개포동,개포6차우성아파트1동~8동,79.97,202205,27,216000.0,2,1987.0
3,서울특별시 강남구 개포동,개포래미안포레스트,102.32,202204,1,369000.0,13,2020.0
4,서울특별시 강남구 개포동,개포래미안포레스트,136.06,202205,2,420000.0,17,2020.0
...,...,...,...,...,...,...,...,...
12679,서울특별시 중랑구 중화동,한신아파트(103~109),59.76,202203,27,73000.0,20,1997.0
12680,서울특별시 중랑구 중화동,한신아파트(103~109),59.76,202207,20,74000.0,3,1997.0
12681,서울특별시 중랑구 중화동,한신아파트(103~109),84.03,202207,27,91500.0,12,1997.0
12682,서울특별시 중랑구 중화동,한영(101),84.69,202204,9,49900.0,7,2003.0
12683,서울특별시 중랑구 중화동,현대휴앤미(102동),76.43,202204,23,53000.0,6,2007.0

LLM이 알려준 최종 코드 결과를 그대로 복사+붙여넣기하여 notebook 환경에서 실행합니다.

#### 결측치 확인

데이터프레임에 비어 있는 부분이 있는지 확인 후, 있다면 제거하는 방식으로 처리합니다. 이때 참고사항으로 "열"이라고 하면 잘 못 알아듣는 경우가 많아, "row"로 프롬프트를 구성하였습니다.

In [21]:
response = code_chain.invoke("결측치가 있으면 그 row를 제거하고 싶어. 코드를 짜줄래?")

response

```python
# 결측치가 하나라도 포함된 행(row) 제거
df = df.dropna()

# 필요하다면 인덱스 재정렬
df = df.reset_index(drop=True)
```

In [22]:
# 결측치가 하나라도 포함된 행(row) 제거
df = df.dropna()

# 필요하다면 인덱스 재정렬
df = df.reset_index(drop=True)

In [25]:
df

,시군구,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도
0,서울특별시 강남구 개포동,개포6차우성아파트1동~8동,79.97,202204,12,220000.0,4,1987.0
1,서울특별시 강남구 개포동,개포6차우성아파트1동~8동,79.97,202204,21,220000.0,2,1987.0
2,서울특별시 강남구 개포동,개포6차우성아파트1동~8동,79.97,202205,27,216000.0,2,1987.0
3,서울특별시 강남구 개포동,개포래미안포레스트,102.32,202204,1,369000.0,13,2020.0
4,서울특별시 강남구 개포동,개포래미안포레스트,136.06,202205,2,420000.0,17,2020.0
...,...,...,...,...,...,...,...,...
12644,서울특별시 중랑구 중화동,한신아파트(103~109),59.76,202203,27,73000.0,20,1997.0
12645,서울특별시 중랑구 중화동,한신아파트(103~109),59.76,202207,20,74000.0,3,1997.0
12646,서울특별시 중랑구 중화동,한신아파트(103~109),84.03,202207,27,91500.0,12,1997.0
12647,서울특별시 중랑구 중화동,한영(101),84.69,202204,9,49900.0,7,2003.0
12648,서울특별시 중랑구 중화동,현대휴앤미(102동),76.43,202204,23,53000.0,6,2007.0

#### 컬럼명 변경

`전용면적(㎡)` 컬럼의 제곱미터가 특수문자라 사용하기 어려운 것 같아 `전용면적` 컬럼으로 변경합니다.

In [26]:
response = code_chain.invoke("전용면적(㎡) 컬럼을 '전용면적'으로 컬럼 이름을 바꿔주는 코드를 짜줄래?")

response

```python
# '전용면적(㎡)' 컬럼명을 '전용면적'으로 변경
df = df.rename(columns={'전용면적(㎡)': '전용면적'})
```

In [27]:
# 이 곳에 LLM이 알려준 최종 코드 결과를 붙여넣습니다.
# '전용면적(㎡)' 컬럼명을 '전용면적'으로 변경
df = df.rename(columns={'전용면적(㎡)': '전용면적'})

In [28]:
df

,시군구,단지명,전용면적,계약년월,계약일,거래금액(만원),층,건축년도
0,서울특별시 강남구 개포동,개포6차우성아파트1동~8동,79.97,202204,12,220000.0,4,1987.0
1,서울특별시 강남구 개포동,개포6차우성아파트1동~8동,79.97,202204,21,220000.0,2,1987.0
2,서울특별시 강남구 개포동,개포6차우성아파트1동~8동,79.97,202205,27,216000.0,2,1987.0
3,서울특별시 강남구 개포동,개포래미안포레스트,102.32,202204,1,369000.0,13,2020.0
4,서울특별시 강남구 개포동,개포래미안포레스트,136.06,202205,2,420000.0,17,2020.0
...,...,...,...,...,...,...,...,...
12644,서울특별시 중랑구 중화동,한신아파트(103~109),59.76,202203,27,73000.0,20,1997.0
12645,서울특별시 중랑구 중화동,한신아파트(103~109),59.76,202207,20,74000.0,3,1997.0
12646,서울특별시 중랑구 중화동,한신아파트(103~109),84.03,202207,27,91500.0,12,1997.0
12647,서울특별시 중랑구 중화동,한영(101),84.69,202204,9,49900.0,7,2003.0
12648,서울특별시 중랑구 중화동,현대휴앤미(102동),76.43,202204,23,53000.0,6,2007.0

#### 시군구 컬럼 분리

전체가 `서울특별시`이므로 시는 제외하고, 구와 동으로 세부적으로 나눠 데이터를 분석하고자 합니다.

In [32]:
response = code_chain.invoke(
    "시군구 컬럼의 주소는 활용하기 쉽게 시, 군, 구 세 개로 나눠서 '시'는 제외하고 '구' 컬럼과 '동' 컬럼으로 분리해주는 코드를 짜줄래?"
)

response

```python
import pandas as pd

# '시군구' 컬럼을 공백 기준으로 분리
# 예: '서울특별시 강남구 대치동' -> ['서울특별시', '강남구', '대치동']
addr_split = df['시군구'].str.split()

# 첫 번째 요소(시)는 제외하고, 두 번째와 세 번째 요소를 각각 '구', '동' 컬럼에 할당
df['구'] = addr_split.str[1]
df['동'] = addr_split.str[2]

# 필요하다면 기존 '시군구' 컬럼 확인
# print(df[['시군구', '구', '동']].head())
```

In [33]:
# 이 곳에 LLM이 알려준 최종 코드 결과를 붙여넣습니다.
import pandas as pd

# '시군구' 컬럼을 공백 기준으로 분리
# 예: '서울특별시 강남구 대치동' -> ['서울특별시', '강남구', '대치동']
addr_split = df['시군구'].str.split()

# 첫 번째 요소(시)는 제외하고, 두 번째와 세 번째 요소를 각각 '구', '동' 컬럼에 할당
df['구'] = addr_split.str[1]
df['동'] = addr_split.str[2]

# 필요하다면 기존 '시군구' 컬럼 확인
# print(df[['시군구', '구', '동']].head())

In [35]:
df

,시군구,단지명,전용면적,계약년월,계약일,거래금액(만원),층,건축년도,구,동
0,서울특별시 강남구 개포동,개포6차우성아파트1동~8동,79.97,202204,12,220000.0,4,1987.0,강남구,개포동
1,서울특별시 강남구 개포동,개포6차우성아파트1동~8동,79.97,202204,21,220000.0,2,1987.0,강남구,개포동
2,서울특별시 강남구 개포동,개포6차우성아파트1동~8동,79.97,202205,27,216000.0,2,1987.0,강남구,개포동
3,서울특별시 강남구 개포동,개포래미안포레스트,102.32,202204,1,369000.0,13,2020.0,강남구,개포동
4,서울특별시 강남구 개포동,개포래미안포레스트,136.06,202205,2,420000.0,17,2020.0,강남구,개포동
...,...,...,...,...,...,...,...,...,...,...
12644,서울특별시 중랑구 중화동,한신아파트(103~109),59.76,202203,27,73000.0,20,1997.0,중랑구,중화동
12645,서울특별시 중랑구 중화동,한신아파트(103~109),59.76,202207,20,74000.0,3,1997.0,중랑구,중화동
12646,서울특별시 중랑구 중화동,한신아파트(103~109),84.03,202207,27,91500.0,12,1997.0,중랑구,중화동
12647,서울특별시 중랑구 중화동,한영(101),84.69,202204,9,49900.0,7,2003.0,중랑구,중화동
12648,서울특별시 중랑구 중화동,현대휴앤미(102동),76.43,202204,23,53000.0,6,2007.0,중랑구,중화동

#### 계약년월 컬럼 분리

마찬가지로 전체가 2022년이므로 연도는 제외하고, 월 컬럼만 사용하여 세부적으로 데이터를 분석하고자 합니다.

In [36]:
response = code_chain.invoke(
    "계약년월 컬럼에서 계약월을 분리해서 새로운 컬럼으로 만들어주는 코드를 짜줄래?"
)

response

```python
# 계약년월(예: 202401)에서 계약월만 추출하여 새로운 컬럼 생성
# 방법 1: 정수형 기준으로 100으로 나눈 나머지를 사용
df['계약월'] = df['계약년월'] % 100

# 필요 시 두 자리 문자열 형태(예: '01', '12')로도 생성 가능
# df['계약월'] = (df['계약년월'] % 100).astype(str).str.zfill(2)
```

In [39]:
# 계약년월(예: 202401)에서 계약월만 추출하여 새로운 컬럼 생성
# 방법 1: 정수형 기준으로 100으로 나눈 나머지를 사용
df['계약월'] = df['계약년월'] % 100

# 필요 시 두 자리 문자열 형태(예: '01', '12')로도 생성 가능
# df['계약월'] = (df['계약년월'] % 100).astype(str).str.zfill(2)

In [40]:
df

,시군구,단지명,전용면적,계약년월,계약일,거래금액(만원),층,건축년도,구,동,계약월
0,서울특별시 강남구 개포동,개포6차우성아파트1동~8동,79.97,202204,12,220000.0,4,1987.0,강남구,개포동,4
1,서울특별시 강남구 개포동,개포6차우성아파트1동~8동,79.97,202204,21,220000.0,2,1987.0,강남구,개포동,4
2,서울특별시 강남구 개포동,개포6차우성아파트1동~8동,79.97,202205,27,216000.0,2,1987.0,강남구,개포동,5
3,서울특별시 강남구 개포동,개포래미안포레스트,102.32,202204,1,369000.0,13,2020.0,강남구,개포동,4
4,서울특별시 강남구 개포동,개포래미안포레스트,136.06,202205,2,420000.0,17,2020.0,강남구,개포동,5
...,...,...,...,...,...,...,...,...,...,...,...
12644,서울특별시 중랑구 중화동,한신아파트(103~109),59.76,202203,27,73000.0,20,1997.0,중랑구,중화동,3
12645,서울특별시 중랑구 중화동,한신아파트(103~109),59.76,202207,20,74000.0,3,1997.0,중랑구,중화동,7
12646,서울특별시 중랑구 중화동,한신아파트(103~109),84.03,202207,27,91500.0,12,1997.0,중랑구,중화동,7
12647,서울특별시 중랑구 중화동,한영(101),84.69,202204,9,49900.0,7,2003.0,중랑구,중화동,4
12648,서울특별시 중랑구 중화동,현대휴앤미(102동),76.43,202204,23,53000.0,6,2007.0,중랑구,중화동,4

#### 건축년도 컬럼 형 변환

현재 건축년도 컬럼이 **실수형 데이터**로 되어있어 소수점 아래가 불필요하므로, 데이터 타입을 **정수형**으로 바꿔줍니다.

In [41]:
response = code_chain.invoke("건축년도 컬럼의 값이 정수를 가지도록 바꿔주는 코드를 짜줘")

response

```python
# '건축년도' 컬럼을 정수형으로 변환
# 현재 결측치가 없으므로 바로 astype(int) 사용 가능
df['건축년도'] = df['건축년도'].astype(int)
```

In [42]:
# 이 곳에 LLM이 알려준 최종 코드 결과를 붙여넣습니다.
# '건축년도' 컬럼을 정수형으로 변환
# 현재 결측치가 없으므로 바로 astype(int) 사용 가능
df['건축년도'] = df['건축년도'].astype(int)

In [43]:
df

,시군구,단지명,전용면적,계약년월,계약일,거래금액(만원),층,건축년도,구,동,계약월
0,서울특별시 강남구 개포동,개포6차우성아파트1동~8동,79.97,202204,12,220000.0,4,1987,강남구,개포동,4
1,서울특별시 강남구 개포동,개포6차우성아파트1동~8동,79.97,202204,21,220000.0,2,1987,강남구,개포동,4
2,서울특별시 강남구 개포동,개포6차우성아파트1동~8동,79.97,202205,27,216000.0,2,1987,강남구,개포동,5
3,서울특별시 강남구 개포동,개포래미안포레스트,102.32,202204,1,369000.0,13,2020,강남구,개포동,4
4,서울특별시 강남구 개포동,개포래미안포레스트,136.06,202205,2,420000.0,17,2020,강남구,개포동,5
...,...,...,...,...,...,...,...,...,...,...,...
12644,서울특별시 중랑구 중화동,한신아파트(103~109),59.76,202203,27,73000.0,20,1997,중랑구,중화동,3
12645,서울특별시 중랑구 중화동,한신아파트(103~109),59.76,202207,20,74000.0,3,1997,중랑구,중화동,7
12646,서울특별시 중랑구 중화동,한신아파트(103~109),84.03,202207,27,91500.0,12,1997,중랑구,중화동,7
12647,서울특별시 중랑구 중화동,한영(101),84.69,202204,9,49900.0,7,2003,중랑구,중화동,4
12648,서울특별시 중랑구 중화동,현대휴앤미(102동),76.43,202204,23,53000.0,6,2007,중랑구,중화동,4

#### 거래 금액 억 단위로 변환

서울 주택 가격의 경우, 일반적으로 억 단위로 표현하는 것이 가독성이 좋기 때문에 **만원 단위**를 **억 단위**로 바꿔줍니다.

> 프롬프트를 작성할 때 만과 억의 관계에 대해 추가적으로 주면 더 LLM이 코드 작성을 더 잘 수행해줍니다.

In [44]:
response = code_chain.invoke(
    "거래금액(만원) 컬럼을 거래금액(억) 컬럼으로 새롭게 만들어주는 코드를 짜줘. 참고로 10000으로 나눠주면 돼"
)

response

```python
# 거래금액(만원) 컬럼을 10000으로 나누어 거래금액(억) 컬럼 생성
df['거래금액(억)'] = df['거래금액(만원)'] / 10000
```

In [48]:
# 거래금액(만원) 컬럼을 10000으로 나누어 거래금액(억) 컬럼 생성
df['거래금액(억)'] = df['거래금액(만원)'] / 10000

In [49]:
df

,시군구,단지명,전용면적,계약년월,계약일,거래금액(만원),층,건축년도,구,동,계약월,거래금액(억)
0,서울특별시 강남구 개포동,개포6차우성아파트1동~8동,79.97,202204,12,220000.0,4,1987,강남구,개포동,4,22.00
1,서울특별시 강남구 개포동,개포6차우성아파트1동~8동,79.97,202204,21,220000.0,2,1987,강남구,개포동,4,22.00
2,서울특별시 강남구 개포동,개포6차우성아파트1동~8동,79.97,202205,27,216000.0,2,1987,강남구,개포동,5,21.60
3,서울특별시 강남구 개포동,개포래미안포레스트,102.32,202204,1,369000.0,13,2020,강남구,개포동,4,36.90
4,서울특별시 강남구 개포동,개포래미안포레스트,136.06,202205,2,420000.0,17,2020,강남구,개포동,5,42.00
...,...,...,...,...,...,...,...,...,...,...,...,...
12644,서울특별시 중랑구 중화동,한신아파트(103~109),59.76,202203,27,73000.0,20,1997,중랑구,중화동,3,7.30
12645,서울특별시 중랑구 중화동,한신아파트(103~109),59.76,202207,20,74000.0,3,1997,중랑구,중화동,7,7.40
12646,서울특별시 중랑구 중화동,한신아파트(103~109),84.03,202207,27,91500.0,12,1997,중랑구,중화동,7,9.15
12647,서울특별시 중랑구 중화동,한영(101),84.69,202204,9,49900.0,7,2003,중랑구,중화동,4,4.99
12648,서울특별시 중랑구 중화동,현대휴앤미(102동),76.43,202204,23,53000.0,6,2007,중랑구,중화동,4,5.30

#### 유형 컬럼 생성

주택 평수를 이용하여 주택 유형을 분류하기 위해 연속형 변수인 전용면적 컬럼을 범주형 변수인 유형 컬럼으로 만들어줍니다. 프롬프트가 길어질 경우 파이썬 문자열 포맷팅 방법을 이용하여 아래와 같이 가독성 좋게 프롬프트를 만들 수 있습니다.

> 복잡한 로직을 LLM에게 요구하는 경우, LLM이 함수를 생성하여 코드를 알려주는 경우가 있는데 이때 에러가 자주 발생하므로, "한 줄로"라는 명령어를 프롬프트에 추가해주면 도움이 될 수 있습니다.

In [50]:
ref = """
1) 전용면적이 60 이하면 소형,
2) 60보다 크고 85 이하면 중형,
3) 85보다 크고 102 이하면 중대형,
4) 102보다 크면 대형으로 분류됩니다
"""

response = code_chain.invoke(
    "{}를 참고하여, 전용면적 컬럼을 유형 컬럼으로 새롭게 만들어주는 코드 한 줄로 짜줄래?".format(ref)
)

response

```python
df['유형'] = pd.cut(df['전용면적'], bins=[-float('inf'), 60, 85, 102, float('inf')], labels=['소형', '중형', '중대형', '대형'])  # 전용면적 기준으로 유형 컬럼 생성
```

In [51]:
# 이 곳에 LLM이 알려준 최종 코드 결과를 붙여넣습니다.
df['유형'] = pd.cut(df['전용면적'], bins=[-float('inf'), 60, 85, 102, float('inf')], labels=['소형', '중형', '중대형', '대형'])  # 전용면적 기준으로 유형 컬럼 생성

In [52]:
df

,시군구,단지명,전용면적,계약년월,계약일,거래금액(만원),층,건축년도,구,동,계약월,거래금액(억),유형
0,서울특별시 강남구 개포동,개포6차우성아파트1동~8동,79.97,202204,12,220000.0,4,1987,강남구,개포동,4,22.00,중형
1,서울특별시 강남구 개포동,개포6차우성아파트1동~8동,79.97,202204,21,220000.0,2,1987,강남구,개포동,4,22.00,중형
2,서울특별시 강남구 개포동,개포6차우성아파트1동~8동,79.97,202205,27,216000.0,2,1987,강남구,개포동,5,21.60,중형
3,서울특별시 강남구 개포동,개포래미안포레스트,102.32,202204,1,369000.0,13,2020,강남구,개포동,4,36.90,대형
4,서울특별시 강남구 개포동,개포래미안포레스트,136.06,202205,2,420000.0,17,2020,강남구,개포동,5,42.00,대형
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12644,서울특별시 중랑구 중화동,한신아파트(103~109),59.76,202203,27,73000.0,20,1997,중랑구,중화동,3,7.30,소형
12645,서울특별시 중랑구 중화동,한신아파트(103~109),59.76,202207,20,74000.0,3,1997,중랑구,중화동,7,7.40,소형
12646,서울특별시 중랑구 중화동,한신아파트(103~109),84.03,202207,27,91500.0,12,1997,중랑구,중화동,7,9.15,중형
12647,서울특별시 중랑구 중화동,한영(101),84.69,202204,9,49900.0,7,2003,중랑구,중화동,4,4.99,중형
12648,서울특별시 중랑구 중화동,현대휴앤미(102동),76.43,202204,23,53000.0,6,2007,중랑구,중화동,4,5.30,중형

#### 전용면적 컬럼을 평 컬럼으로 변경하기: 우리에게 좀더 익숙한 단위인 평으로 컬럼으로 변경해줍니다.
- 1평은 3.3제곱미터라는 정보를 프롬프트에 추가해주면 결과가 더 잘 생성됩니다.
- 가독성을 위해 LLM에게 소수점 아래 둘째자리까지 나타내달라고 요청합니다.

In [53]:
response = code_chain.invoke(
    "1평은 3.3 제곱미터이니, 전용면적 컬럼의 값들을 3.3으로 나눈 평 컬럼을 새롭게 만들어주는 코드를 짜줘. 소수점 둘째자리까지 나타내줘."
)

response

```python
# 전용면적(㎡)을 3.3으로 나누어 평 컬럼 생성
# 소수점 둘째자리까지 반올림하여 저장
df['평'] = (df['전용면적'] / 3.3).round(2)
```

In [56]:
# 이 곳에 LLM이 알려준 최종 코드 결과를 붙여넣습니다.
# 전용면적(㎡)을 3.3으로 나누어 평 컬럼 생성
# 소수점 둘째자리까지 반올림하여 저장
df['평'] = (df['전용면적'] / 3.3).round(2)

In [57]:
df

,시군구,단지명,전용면적,계약년월,계약일,거래금액(만원),층,건축년도,구,동,계약월,거래금액(억),유형,평
0,서울특별시 강남구 개포동,개포6차우성아파트1동~8동,79.97,202204,12,220000.0,4,1987,강남구,개포동,4,22.00,중형,24.23
1,서울특별시 강남구 개포동,개포6차우성아파트1동~8동,79.97,202204,21,220000.0,2,1987,강남구,개포동,4,22.00,중형,24.23
2,서울특별시 강남구 개포동,개포6차우성아파트1동~8동,79.97,202205,27,216000.0,2,1987,강남구,개포동,5,21.60,중형,24.23
3,서울특별시 강남구 개포동,개포래미안포레스트,102.32,202204,1,369000.0,13,2020,강남구,개포동,4,36.90,대형,31.01
4,서울특별시 강남구 개포동,개포래미안포레스트,136.06,202205,2,420000.0,17,2020,강남구,개포동,5,42.00,대형,41.23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12644,서울특별시 중랑구 중화동,한신아파트(103~109),59.76,202203,27,73000.0,20,1997,중랑구,중화동,3,7.30,소형,18.11
12645,서울특별시 중랑구 중화동,한신아파트(103~109),59.76,202207,20,74000.0,3,1997,중랑구,중화동,7,7.40,소형,18.11
12646,서울특별시 중랑구 중화동,한신아파트(103~109),84.03,202207,27,91500.0,12,1997,중랑구,중화동,7,9.15,중형,25.46
12647,서울특별시 중랑구 중화동,한영(101),84.69,202204,9,49900.0,7,2003,중랑구,중화동,4,4.99,중형,25.66
12648,서울특별시 중랑구 중화동,현대휴앤미(102동),76.43,202204,23,53000.0,6,2007,중랑구,중화동,4,5.30,중형,23.16

#### 잉여 칼럼 제거하기

컬럼을 새롭게 생성하는 과정에서 더이상 필요 없어진 컬럼을 제거합니다.

In [58]:
response = code_chain.invoke(
    "시군구, 전용면적, 계약년월, 계약일, 거래금액(만원) 컬럼들은 더이상 필요 없을 것 같은데 삭제하는 코드를 짜줘."
)

response

```python
# 더이상 필요 없는 컬럼 삭제
df = df.drop(columns=['시군구', '전용면적', '계약년월', '계약일', '거래금액(만원)'])

# 삭제 결과 확인
df.head()
```

In [61]:
# 이 곳에 LLM이 알려준 최종 코드 결과를 붙여넣습니다.
# 더 이상 필요 없는 컬럼 삭제
df = df.drop(columns=['시군구', '전용면적', '계약년월', '계약일', '거래금액(만원)'])

In [62]:
df

                  단지명   층  건축년도    구    동  계약월  거래금액(억)  유형      평
0      개포6차우성아파트1동~8동   4  1987  강남구  개포동    4    22.00  중형  24.23
1      개포6차우성아파트1동~8동   2  1987  강남구  개포동    4    22.00  중형  24.23
2      개포6차우성아파트1동~8동   2  1987  강남구  개포동    5    21.60  중형  24.23
3           개포래미안포레스트  13  2020  강남구  개포동    4    36.90  대형  31.01
4           개포래미안포레스트  17  2020  강남구  개포동    5    42.00  대형  41.23
...               ...  ..   ...  ...  ...  ...      ...  ..    ...
12644  한신아파트(103~109)  20  1997  중랑구  중화동    3     7.30  소형  18.11
12645  한신아파트(103~109)   3  1997  중랑구  중화동    7     7.40  소형  18.11
12646  한신아파트(103~109)  12  1997  중랑구  중화동    7     9.15  중형  25.46
12647         한영(101)   7  2003  중랑구  중화동    4     4.99  중형  25.66
12648     현대휴앤미(102동)   6  2007  중랑구  중화동    4     5.30  중형  23.16

[12649 rows x 9 columns]

#### 최종 데이터프레임 저장

앞선 데이터 전처리 과정을 거친 최종 데이터 프레임을 `csv` 파일 형식으로 저장합니다. `to_csv`를 사용하면 `Dataframe`을 `csv`로 저장할 수 있습니다.

In [63]:
df.to_csv("./seoul_apart_preprocess.csv", index=False)